In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("file.csv")
df

,Date,Bill No.,Pan No.,particulars,customer,Business,Bank,Total Purchase,Rate,Unnamed: 9,...,customer gold,Total,Rate.1,Total amount,Wages,other,stone,Discount,Total amount .1,Grand Total
0,16.0,1.0,NaN,Tilahari,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,9.5,97200.0,9234.0,1200.0,NaN,NaN,NaN,1200.0,10434.0
1,19.0,2.0,solved,Mala,NaN,NaN,NaN,NaN,NaN,0.00,...,NaN,48.0,98000.0,47040.0,1200.0,NaN,NaN,NaN,1200.0,48240.0
2,19.0,3.0,solved,marwadi,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,23.1,95600.0,22084.0,600.0,NaN,NaN,NaN,600.0,22684.0
3,20.0,4.0,NaN,Sikri and Locket,NaN,NaN,NaN,0.00,NaN,0.00,...,63.0,84.7,95600.0,80973.0,1200.0,700.0,200.0,NaN,2100.0,83073.0
4,25.0,5.0,NaN,Authi,NaN,NaN,NaN,0.00,NaN,0.00,...,28.0,14.7,95300.0,14009.0,1200.0,NaN,NaN,NaN,1200.0,15209.0
5,2.0,6.0,damaged,NaN,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0
6,25.0,7.0,NaN,Braclet,NaN,NaN,NaN,0.00,NaN,0.00,...,109.0,8.7,96000.0,8352.0,1500.0,NaN,NaN,NaN,1500.0,9852.0
7,25.0,8.0,NaN,Authi,NaN,NaN,NaN,0.00,NaN,0.00,...,19.0,15.3,96000.0,14688.0,1200.0,NaN,NaN,NaN,1200.0,15888.0
8,25.0,9.0,NaN,Sikri,NaN,NaN,NaN,0.00,NaN,0.00,...,55.0,3.4,96000.0,3264.0,1200.0,NaN,NaN,NaN,1200.0,4464.0
9,25.0,10.0,NaN,Sikri,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,159.6,95800.0,152897.0,2000.0,NaN,NaN,NaN,2000.0,154897.0
10,25.0,11.0,NaN,Sikri,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,129.1,NaN,0.0,1500.0,NaN,NaN,NaN,1500.0,1500.0
11,5.0,12.0,damaged,NaN,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0
12,25.0,13.0,NaN,Locket,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,13.4,95600.0,12810.0,800.0,NaN,500.0,NaN,1300.0,14110.0
13,26.0,14.0,NaN,Top,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,31.1,NaN,0.0,1500.0,NaN,400.0,NaN,1900.0,1900.0
14,26.0,15.0,NaN,Locket,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,79.9,95800.0,76544.0,1200.0,NaN,NaN,NaN,1200.0,77744.0
15,29.0,16.0,NaN,Sikri,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,109.1,97800.0,106700.0,1500.0,NaN,NaN,NaN,1500.0,108200.0
16,31.0,17.0,NaN,Tilhari,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,35.2,96700.0,34038.0,1200.0,NaN,NaN,NaN,1200.0,35238.0
17,31.0,18.0,NaN,Tilhari,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,40.3,96700.0,38970.0,1200.0,NaN,NaN,NaN,1200.0,40170.0
18,2.0,19.0,NaN,Bala,NaN,NaN,NaN,0.00,NaN,0.00,...,88.0,30.3,97100.0,29421.0,2000.0,NaN,NaN,NaN,2000.0,NaN
19,2.0,20.0,NaN,Sikri,NaN,NaN,NaN,0.00,NaN,0.00,...,40.0,70.0,96900.0,67830.0,1200.0,NaN,NaN,NaN,1200.0,NaN
20,6.0,51.0,609820089,Ratnayan Jyasa Pvt. Ltd.,NaN,69.62,NaN,69.62,8170.5,568830.21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,7.0,21.0,NaN,Jhumka,NaN,NaN,NaN,0.00,NaN,0.00,...,29.7,27.6,96100.0,26524.0,1200.0,NaN,NaN,NaN,1200.0,NaN
22,7.0,22.0,NaN,Jhumka,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,57.2,95400.0,54569.0,1200.0,NaN,NaN,NaN,1200.0,NaN
23,8.0,23.0,NaN,Hina Authi,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,54.4,95500.0,51952.0,600.0,NaN,NaN,NaN,600.0,NaN
24,12.0,24.0,NaN,Braclet *2,NaN,NaN,NaN,0.00,NaN,0.00,...,200.0,11.7,95300.0,11150.0,3000.0,NaN,1120.0,NaN,4120.0,NaN
25,13.0,25.0,NaN,Ganesh Authi,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,56.1,95600.0,53632.0,1500.0,NaN,NaN,NaN,1500.0,NaN
26,14.0,26.0,NaN,Sikri and Locket,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,222.2,97400.0,216423.0,3000.0,NaN,NaN,NaN,3000.0,NaN
27,14.0,27.0,NaN,Authi,NaN,NaN,NaN,0.00,NaN,0.00,...,34.0,21.7,95600.0,20745.0,1000.0,NaN,NaN,NaN,1000.0,NaN
28,17.0,28.0,NaN,Guli Mangalsutra,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,57.2,95300.0,54512.0,1200.0,NaN,200.0,NaN,1400.0,NaN
29,21.0,29.0,NaN,Bala,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,114.0,97800.0,111492.0,2000.0,NaN,NaN,NaN,2000.0,NaN
30,22.0,30.0,NaN,Sikri,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,327.0,93100.0,304437.0,1500.0,NaN,NaN,NaN,1500.0,NaN
31,22.0,31.0,NaN,Mundra,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,22.2,93100.0,20668.0,500.0,NaN,NaN,NaN,500.0,NaN
32,22.0,32.0,NaN,Mundra,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,22.1,93100.0,20575.0,500.0,NaN,NaN,NaN,500.0,NaN
33,23.0,33.0,NaN,Tilhari,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,30.5,93800.0,28609.0,1500.0,NaN,NaN,NaN,1500.0,NaN
34,24.0,34.0,NaN,Tilhari,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,36.7,93800.0,34425.0,1500.0,NaN,NaN,NaN,1500.0,NaN
35,25.0,35.0,NaN,Top,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,56.6,95800.0,54223.0,1200.0,NaN,NaN,NaN,1200.0,NaN
36,26.0,36.0,solved,Guli Mangalsutra,NaN,NaN,NaN,0.00,NaN,0.00,...,29.6,17.0,93800.0,15946.0,1500.0,NaN,NaN,NaN,1500.0,NaN
37,NaN,37.0,damaged,NaN,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
38,30.0,6.0,606892971,H.B Jewellers and Investment Pvt. Ltd.,NaN,68.89,NaN,69.89,7930.5,554262.65,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,1.0,38.0,NaN,Tilhari*3,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,71.3,95300.0,67949.0,4500.0,NaN,NaN,NaN,4500.0,72449.0
40,2.0,39.0,NaN,Sikri,NaN,NaN,NaN,NaN,NaN,0.00,...,NaN,55.8,91500.0,51057.0,1500.0,NaN,NaN,NaN,1500.0,52557.0
41,2.0,40.0,NaN,Jhumka,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,57.6,91500.0,52704.0,1500.0,NaN,NaN,NaN,1500.0,54204.0
42,3.0,41.0,NaN,Kanye Sikri,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,57.6,93500.0,53856.0,1500.0,NaN,NaN,NaN,1500.0,55356.0
43,6.0,42.0,NaN,Necklace,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,90.8,93000.0,84444.0,1500.0,NaN,NaN,NaN,1500.0,85944.0
44,7.0,43.0,NaN,Bala Chura,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,117.7,93800.0,110403.0,2000.0,NaN,NaN,NaN,2000.0,112403.0
45,11.0,44.0,solved,Sikri,NaN,NaN,NaN,0.00,NaN,0.00,...,144.0,21.0,92500.0,19425.0,1500.0,NaN,NaN,NaN,1500.0,20925.0
46,11.0,45.0,NaN,Nau Ratna Locket,NaN,NaN,NaN,0.00,NaN,0.00,...,53.8,6.5,92500.0,6013.0,1200.0,1500.0,500.0,NaN,3200.0,9213.0
47,12.0,46.0,NaN,Jhumka,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,64.7,91400.0,59136.0,1500.0,NaN,NaN,NaN,1500.0,60636.0
48,12.0,47.0,NaN,Tilhari,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,31.2,91600.0,28579.0,1500.0,NaN,NaN,NaN,1500.0,30079.0
49,12.0,48.0,NaN,Necklace,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,167.5,95800.0,160465.0,1800.0,NaN,NaN,NaN,1800.0,162265.0
50,12.0,49.0,NaN,Sikri and Locket,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,68.1,93800.0,63878.0,2200.0,NaN,550.0,NaN,2750.0,66628.0
51,12.0,50.0,NaN,Tilhari,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,31.1,93800.0,29172.0,1500.0,NaN,NaN,NaN,1500.0,30672.0
52,14.0,51.0,NaN,Authi,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,56.2,91800.0,51592.0,1500.0,NaN,850.0,NaN,2350.0,53942.0
53,15.0,52.0,NaN,Guli*6,NaN,NaN,NaN,0.00,NaN,0.00,...,NaN,30.5,91500.0,27908.0,1000.0,NaN,NaN,NaN,1000.0,28908.0
54,16.0,53.0,NaN,Mangalsutra,NaN,NaN,NaN,0.00,NaN,0.00,...,40.0,77.1,93600.0,72166.0,1500.0,1000.0,960.0,NaN,3460.0,75626.0
55,30.0,54.0,NaN,Chaka,NaN,NaN,NaN,0.00,NaN,0.00,...,38.2,9.1,93600.0,8518.0,1000.0,NaN,NaN,NaN,1000.0,9518.0

In [3]:
features = df[['particulars','Grand Total']]
features

                               particulars  Grand Total
0                                 Tilahari      10434.0
1                                     Mala      48240.0
2                                  marwadi      22684.0
3                         Sikri and Locket      83073.0
4                                    Authi      15209.0
5                                      NaN          0.0
6                                  Braclet       9852.0
7                                    Authi      15888.0
8                                    Sikri       4464.0
9                                    Sikri     154897.0
10                                   Sikri       1500.0
11                                     NaN          0.0
12                                  Locket      14110.0
13                                     Top       1900.0
14                                  Locket      77744.0
15                                   Sikri     108200.0
16                                 Tilhari      35238.0
17                                 Tilhari      40170.0
18                                    Bala          NaN
19                                   Sikri          NaN
20                Ratnayan Jyasa Pvt. Ltd.          NaN
21                                  Jhumka          NaN
22                                  Jhumka          NaN
23                              Hina Authi          NaN
24                              Braclet *2          NaN
25                            Ganesh Authi          NaN
26                        Sikri and Locket          NaN
27                                   Authi          NaN
28                        Guli Mangalsutra          NaN
29                                    Bala          NaN
30                                   Sikri          NaN
31                                  Mundra          NaN
32                                  Mundra          NaN
33                                 Tilhari          NaN
34                                 Tilhari          NaN
35                                     Top          NaN
36                        Guli Mangalsutra          NaN
37                                     NaN          NaN
38  H.B Jewellers and Investment Pvt. Ltd.          NaN
39                               Tilhari*3      72449.0
40                                   Sikri      52557.0
41                                  Jhumka      54204.0
42                             Kanye Sikri      55356.0
43                                Necklace      85944.0
44                              Bala Chura     112403.0
45                                   Sikri      20925.0
46                        Nau Ratna Locket       9213.0
47                                  Jhumka      60636.0
48                                 Tilhari      30079.0
49                                Necklace     162265.0
50                        Sikri and Locket      66628.0
51                                 Tilhari      30672.0
52                                   Authi      53942.0
53                                  Guli*6      28908.0
54                             Mangalsutra      75626.0
55                                   Chaka       9518.0

In [13]:
features= features.dropna()

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error
import numpy as np

In [31]:
X = features.drop("particulars",axis=1)
y = features[["particulars"]]
X_train,X_test,y_train,y_test = train_test_split(features["particulars"],y,test_size=0.2)
model = DecisionTreeRegressor()

In [35]:
X_train

0             Tilahari
2              marwadi
40               Sikri
1                 Mala
51             Tilhari
44          Bala Chura
46    Nau Ratna Locket
8                Sikri
9                Sikri
13                 Top
4                Authi
3     Sikri and Locket
43            Necklace
52               Authi
15               Sikri
41              Jhumka
14              Locket
42         Kanye Sikri
17             Tilhari
54         Mangalsutra
39           Tilhari*3
45               Sikri
49            Necklace
12              Locket
7                Authi
16             Tilhari
Name: particulars, dtype: object

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error
import numpy as np

df = pd.DataFrame(features)

X_train, X_test, y_train, y_test = train_test_split(df['particulars'], df['Grand Total'], test_size=0.2, random_state=42)

model = make_pipeline(CountVectorizer(), LinearRegression())

model.fit(X_train, y_train)


predictions = model.predict(X_test)

names = input("Enter the name of the jewellery:")
name = [names]
predicted_price = model.predict(name)
print(f'Predicted Price for {names}: Rs.{predicted_price[0]}')

Enter the name of the jewellery:tilahari
Predicted Price for tilahari: Rs.10433.999999999854

In [53]:
df = pd.DataFrame(features)
df

         particulars  Grand Total
0           Tilahari      10434.0
1               Mala      48240.0
2            marwadi      22684.0
3   Sikri and Locket      83073.0
4              Authi      15209.0
6            Braclet       9852.0
7              Authi      15888.0
8              Sikri       4464.0
9              Sikri     154897.0
10             Sikri       1500.0
12            Locket      14110.0
13               Top       1900.0
14            Locket      77744.0
15             Sikri     108200.0
16           Tilhari      35238.0
17           Tilhari      40170.0
39         Tilhari*3      72449.0
40             Sikri      52557.0
41            Jhumka      54204.0
42       Kanye Sikri      55356.0
43          Necklace      85944.0
44        Bala Chura     112403.0
45             Sikri      20925.0
46  Nau Ratna Locket       9213.0
47            Jhumka      60636.0
48           Tilhari      30079.0
49          Necklace     162265.0
50  Sikri and Locket      66628.0
51           Tilhari      30672.0
52             Authi      53942.0
53            Guli*6      28908.0
54       Mangalsutra      75626.0
55             Chaka       9518.0